#{{ if not .Values.disableConsulConsulAgent }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: consul-agent
  name: consul-agent
  namespace: "{{ .Values.nsPrefix }}"
spec:
  replicas: {{ .Values.consulAgentReplicas }}
  selector:
    matchLabels:
      app: consul-agent
  template:
    metadata:
      labels:
        app: consul-agent
      name: consul-agent
    spec:
      containers:
      - image: "{{ .Values.consulimageRegistry }}:{{ .Values.consuldockerTag }}"
        command: ["/usr/local/bin/docker-entrypoint.sh"]
        args: ["agent","-client","0.0.0.0","-enable-script-checks","-join","consul-server.{{ .Values.nsPrefix }}"]
        name: consul-server
        volumeMounts:
        - mountPath: /consul/config
          name: consul-agent-config
          subPath: {{ .Values.nsPrefix }}/consul/consul-agent-config
      volumes:
        - name: consul-agent-config
          persistentVolumeClaim:
            claimName: shared-data-claim

      # - hostPath:
      #     path: {{ .Values.rootHostPath }}/{{ .Values.nsPrefix }}/consul/consul-agent-config
      #   name: consul-agent-config
#{{ end }}
