apiVersion: v1
kind: ConfigMap
metadata:
  name: global-onap-configmap
  namespace: "{{ .Values.nsPrefix }}"
data:
{{ .Files.Get "onap-parameters.yaml" | indent 2 }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-data-claim
  namespace: "{{ .Values.nsPrefix }}"
spec:
  storageClassName: onap-shared-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}
  namespace: "{{ .Values.nsPrefix }}"
spec:
  # nodeSelector:
  #   config: master
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image.repository }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      envFrom:
        - configMapRef:
            name: global-onap-configmap
      env:
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: NAMESPACE_PREFIX
        value: {{ .Values.nsPrefix }}
      - name: DOCKER_SHARE_PATH
        value: {{ .Values.dockerSharePath }}
      volumeMounts:
      - name: config-init-root
        mountPath: /config-init/
  volumes:
    - name: config-init-root
      persistentVolumeClaim:
        claimName: shared-data-claim
      # hostPath:
      #   path: {{ .Values.dockerSharePath }}
  restartPolicy: Never
