#{{ if not .Values.disableMessageRouterDmaap }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: message-router-dmaap
  namespace: "{{ .Values.nsPrefix }}"
spec:
  replicas: {{ .Values.dmaapReplicas }}
  selector:
    matchLabels:
      app: dmaap
  template:
    metadata:
      labels:
        app: dmaap
      name: message-router-dmaap
    spec:
      initContainers:
      - command:
        - /root/ready.py
        args:
        - --container-name
        - global-kafka
        - --container-name
        - zookeeper
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: {{ .Values.image.readiness }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: dmaap-readiness
      containers:
      - image: {{ .Values.image.dmaap }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: dmaap
        ports:
        - containerPort: 3904
        - containerPort: 3905
        readinessProbe:
          tcpSocket:
            port: 3904
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        
        - mountPath: /appl/dmaapMR1/bundleconfig/etc/appprops/MsgRtrApi.properties
          name: config
          subPath: {{ .Values.nsPrefix }}/message-router/dmaap/MsgRtrApi.properties

        - mountPath: /appl/dmaapMR1/etc/cadi.properties
          name: config
          subPath: {{ .Values.nsPrefix }}/message-router/dmaap/cadi.properties

        - mountPath: /appl/dmaapMR1/etc/keyfile
          name: config
          subPath: {{ .Values.nsPrefix }}/message-router/dmaap/mykey

      restartPolicy: Always
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime

      - name: config
        persistentVolumeClaim:
          claimName: shared-data-claim


      # - name: appprops
      #   persistentVolumeClaim:
      #     claimName: shared-data-claim
      #   hostPath:
      #     path: {{ .Values.dataRootDir }}/{{ .Values.nsPrefix }}/message-router/dmaap/MsgRtrApi.properties
      # - name: cadi
      #   persistentVolumeClaim:
      #     claimName: shared-data-claim
      #   hostPath:
      #     path: {{ .Values.dataRootDir }}/{{ .Values.nsPrefix }}/message-router/dmaap/cadi.properties
      # - name: mykey
      #   persistentVolumeClaim:
      #     claimName: shared-data-claim
      #   hostPath:
      #     path: {{ .Values.dataRootDir }}/{{ .Values.nsPrefix }}/message-router/dmaap/mykey
      imagePullSecrets:
      - name: "{{ .Values.nsPrefix }}-docker-registry-key"
{{ end }}
